# Generated by Django 5.2.6 on 2025-09-15 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0002_2_10'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='plan name')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('individual', 'Premium Individual'), ('duo', 'Premium Duo'), ('family', 'Premium Family'), ('student', 'Premium Student')], max_length=20, unique=True, verbose_name='plan type')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20, verbose_name='billing cycle')),
                ('max_members', models.PositiveIntegerField(default=1, help_text='Maximum number of members allowed (for family/duo plans)', verbose_name='maximum members')),
                ('features', models.JSONField(default=dict, help_text='Dictionary of features included in this plan', verbose_name='features')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently available for subscription', verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stripe_price', models.ForeignKey(blank=True, help_text='The associated Stripe Price object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.price')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['price'],
            },
        ),
    ]
