# Generated by Django 5.2.6 on 2026-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_string',
            field=models.CharField(blank=True, help_text='The Stripe Price ID as a string (for direct API usage)', max_length=255, null=True, verbose_name='stripe price id string'),
        ),
    ]
