# Generated by Django 5.2.6 on 2025-09-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_free',
            field=models.BooleanField(default=False, help_text='Whether the user has an ad-free experience'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='audio_quality',
            field=models.CharField(choices=[('low', 'Low (96 kbps)'), ('medium', 'Medium (160 kbps)'), ('high', 'High (320 kbps)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duo_partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duo_partner_of', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_members_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of family members allowed (0 for no family plan)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_plan_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_offline_mode',
            field=models.BooleanField(default=False, help_text='Whether the user can download music for offline listening'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Whether the user is a verified student'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skip_limit',
            field=models.PositiveIntegerField(default=6, help_text='Number of skips allowed per hour'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_verification_date',
            field=models.DateField(blank=True, help_text='When the student status was last verified', null=True),
        ),
    ]
