# Generated by Django 5.2.6 on 2026-02-03 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_distance_learning',
            field=models.BooleanField(default=False, help_text='Whether the student is in a distance learning program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth (must be at least 13 years old)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_enrollment_date',
            field=models.DateField(blank=True, help_text='Date when student enrollment started', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_graduation_date',
            field=models.DateField(blank=True, help_text='Expected or actual graduation date', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_school_email',
            field=models.EmailField(blank=True, help_text='School-issued email address for verification', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_school_name',
            field=models.CharField(blank=True, help_text='Name of the educational institution', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_method', models.CharField(choices=[('email', 'School Email Verification'), ('document', 'Document Upload')], default='email', max_length=20)),
                ('school_email', models.EmailField(blank=True, help_text='School-issued email address', max_length=254, null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the school email has been verified')),
                ('document_type', models.CharField(blank=True, choices=[('school_id', 'School ID Card'), ('class_schedule', 'Class Schedule'), ('transcript', 'Transcript'), ('enrollment_letter', 'Enrollment Verification Letter')], max_length=30, null=True)),
                ('document_file', models.ImageField(blank=True, help_text='Uploaded verification document', null=True, upload_to='student_verification/')),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name_on_document', models.CharField(blank=True, help_text='Full name as it appears on the document', max_length=200, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if verification was rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from reviewer', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which verification was submitted', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from verification submission', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin user who reviewed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Verification',
                'verbose_name_plural': 'Student Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
