# Generated by Django 5.2.6 on 2026-02-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_distance_learning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Artist biography (enriched from external sources)', null=True),
        ),
        migrations.AlterField(
            model_name='studentverification',
            name='verification_method',
            field=models.CharField(choices=[('email', 'School Email Verification'), ('document', 'Document Upload')], default='email', help_text='Both email and document are required, but this field indicates primary method', max_length=20),
        ),
    ]
