# Generated by Django 5.2.6 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_access_token',
            field=models.TextField(blank=True, help_text='Spotify OAuth access token', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_refresh_token',
            field=models.TextField(blank=True, help_text='Spotify OAuth refresh token', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the Spotify access token expires', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_user_id',
            field=models.CharField(blank=True, help_text='Spotify user ID', max_length=255, null=True),
        ),
    ]
