# Generated by Django 5.2.11 on 2026-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_refresh_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_user_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastfm_password_hash',
            field=models.CharField(blank=True, help_text='Last.fm password hash (MD5) for authentication', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastfm_username',
            field=models.CharField(blank=True, help_text='Last.fm username', max_length=255, null=True),
        ),
    ]
