# Generated by Django 5.2.11 on 2026-02-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_spotify_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='lastfm_password_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastfm_username',
        ),
    ]
