# Generated by Django 5.1.6 on 2025-03-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
    ]
