# Generated by Django 5.2.6 on 2026-02-04 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_song_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(blank=True, help_text='Confidence measure of whether the track is acoustic (0.0 = not acoustic, 1.0 = acoustic)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.FloatField(blank=True, help_text='Beats per minute (tempo)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='energy',
            field=models.FloatField(blank=True, help_text='Perceptual measure of intensity and power (0.0 = calm, 1.0 = energetic)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_json',
            field=models.JSONField(blank=True, help_text="Timestamped lyrics in LRC-style format: [{'time': 10.5, 'text': 'lyrics...'}]", null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='mood_tag',
            field=models.CharField(blank=True, help_text="Mood classification (e.g., 'happy', 'sad', 'energetic', 'calm')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='valence',
            field=models.FloatField(blank=True, help_text='Musical positiveness (0.0 = sad, 1.0 = happy)', null=True),
        ),
        migrations.CreateModel(
            name='ListeningRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Room name/description', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the room is currently active')),
                ('current_position', models.FloatField(default=0.0, help_text='Current playback position in seconds')),
                ('is_playing', models.BooleanField(default=False, help_text='Whether playback is currently active')),
                ('max_listeners', models.PositiveIntegerField(default=50, help_text='Maximum number of listeners allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_song', models.ForeignKey(blank=True, help_text='Currently playing song', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playing_in_rooms', to='music.song')),
                ('host', models.ForeignKey(help_text='User who created and controls the room', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomListener',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='music.listeningroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SongAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the analytics record')),
                ('daily_plays', models.PositiveIntegerField(default=0, help_text='Number of plays on this date')),
                ('location_city', models.CharField(blank=True, help_text='City where plays occurred (if available)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='Artist who owns the song', on_delete=django.db.models.deletion.CASCADE, related_name='song_analytics', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(help_text='Song being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='music.song')),
            ],
            options={
                'ordering': ['-date', '-daily_plays'],
            },
        ),
        migrations.AddIndex(
            model_name='listeningroom',
            index=models.Index(fields=['host', '-created_at'], name='music_liste_host_id_3c96ae_idx'),
        ),
        migrations.AddIndex(
            model_name='listeningroom',
            index=models.Index(fields=['is_active'], name='music_liste_is_acti_9934a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomlistener',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='songanalytics',
            index=models.Index(fields=['artist', '-date'], name='music_songa_artist__f38b32_idx'),
        ),
        migrations.AddIndex(
            model_name='songanalytics',
            index=models.Index(fields=['song', '-date'], name='music_songa_song_id_981d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='songanalytics',
            index=models.Index(fields=['date', '-daily_plays'], name='music_songa_date_19955e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='songanalytics',
            unique_together={('song', 'date', 'location_city')},
        ),
    ]
