# Generated by Django 5.2.6 on 2026-02-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_song_acousticness_song_bpm_song_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_external_url',
            field=models.URLField(blank=True, help_text='Spotify external URL', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='Spotify album ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_uri',
            field=models.CharField(blank=True, help_text='Spotify album URI', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_external_url',
            field=models.URLField(blank=True, help_text='Spotify external URL', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='Spotify track ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_preview_url',
            field=models.URLField(blank=True, help_text='30-second preview URL from Spotify', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_uri',
            field=models.CharField(blank=True, help_text='Spotify track URI', max_length=255, null=True),
        ),
    ]
