# Generated by Django 5.2.11 on 2026-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_album_spotify_external_url_album_spotify_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='spotify_external_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='album',
            name='spotify_uri',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_external_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_preview_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_uri',
        ),
        migrations.AddField(
            model_name='album',
            name='lastfm_mbid',
            field=models.CharField(blank=True, help_text='Last.fm MusicBrainz ID (MBID)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='lastfm_playcount',
            field=models.PositiveIntegerField(blank=True, help_text='Play count from Last.fm', null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='lastfm_url',
            field=models.URLField(blank=True, help_text='Last.fm album URL', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_listeners',
            field=models.PositiveIntegerField(blank=True, help_text='Number of listeners from Last.fm', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_mbid',
            field=models.CharField(blank=True, help_text='Last.fm MusicBrainz ID (MBID)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_playcount',
            field=models.PositiveIntegerField(blank=True, help_text='Play count from Last.fm', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lastfm_url',
            field=models.URLField(blank=True, help_text='Last.fm track URL', null=True),
        ),
    ]
