# Generated by Django 5.2.11 on 2026-02-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_remove_album_spotify_external_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='lastfm_mbid',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lastfm_playcount',
        ),
        migrations.RemoveField(
            model_name='album',
            name='lastfm_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lastfm_listeners',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lastfm_mbid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lastfm_playcount',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lastfm_url',
        ),
    ]
